# Generated by Django 3.2.6 on 2021-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='count_of_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
